Ajuste no yml 3

diff --git a/.github/workflows/scrape-news.yml b/.github/workflows/scrape-news.yml
--- a/.github/workflows/scrape-news.yml
+++ b/.github/workflows/scrape-news.yml
@@ -3,6 +3,7 @@ on:
   schedule:
     - cron: "0 11 * * *"
   workflow_dispatch:
+
 jobs:
   scrape:
     runs-on: ubuntu-latest
@@ -13,19 +14,18 @@ jobs:
       - name: Setup Node.js
         uses: actions/setup-node@v2
         with:
-          node-version: "16"
+          node-version: "20"
 
       - name: Install dependencies
         run: npm install
 
       - name: Fix vulnerabilities
-        run: npm audit fix || echo "Ignoring audit errors"
+        run: npm audit fix --force
 
       - name: Install system dependencies
         run: |
           sudo apt-get update
           sudo apt-get install -y libnss3-dev libatk1.0-0 libatk-bridge2.0-0 libcups2 libxkbcommon-x11-0 libxcomposite1 libxrandr2 libgbm-dev
-
       - name: Run scraping scripts
         env:
           GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
@@ -33,30 +33,22 @@ jobs:
           echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > api/electric-wave-426309-u0-1bd8b45883b7.json
           for script in scraping/*.js; do
             echo "Running $script"
-            node $script
+            node $script || echo "Error running $script" >> error.log
           done
           for script in idea/*.js; do
             echo "Running $script"
-            node $script
-
+            node $script || echo "Error running $script" >> error.log
+          done
       - name: Upload error logs
         if: failure()
-        run: |
-          if [ -f error.log ]; then
-            echo "Uploading error logs..."
-            actions/upload-artifact@v2 --name error-logs --path error.log
-          else
-            echo "No error logs to upload."
-          fi
+        uses: actions/upload-artifact@v2
+        with:
+          name: error-logs
+          path: error.log
 
       - name: Save full logs
         if: failure()
-        run: |
-          if [ -f error.log ]; then
-            cat error.log
-          else
-            echo "No error logs found."
-          fi
+        run: cat error.log
 
       - name: Report success
         if: success()
