Ajuste no yml

diff --git a/.github/workflows/scrape-news.yml b/.github/workflows/scrape-news.yml
--- a/.github/workflows/scrape-news.yml
+++ b/.github/workflows/scrape-news.yml
@@ -3,24 +3,30 @@ on:
   schedule:
     - cron: "0 11 * * *"
   workflow_dispatch:
+
 jobs:
   scrape:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
         uses: actions/checkout@v2
+
       - name: Setup Node.js
         uses: actions/setup-node@v2
         with:
-          node-version: "16"
+          node-version: "20" # Atualizado para uma versão mais recente do Node.js
+
       - name: Install dependencies
         run: npm install
+
       - name: Fix vulnerabilities
         run: npm audit fix --force
+
       - name: Install system dependencies
         run: |
           sudo apt-get update
           sudo apt-get install -y libnss3-dev libatk1.0-0 libatk-bridge2.0-0 libcups2 libxkbcommon-x11-0 libxcomposite1 libxrandr2 libgbm-dev
+
       - name: Run scraping scripts
         env:
           GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
@@ -28,18 +34,24 @@ jobs:
           echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > api/electric-wave-426309-u0-1bd8b45883b7.json
           for script in scraping/*.js; do
             echo "Running $script"
-            node $script
+            node $script || echo "Error running $script" >> error.log
           done
           for script in idea/*.js; do
             echo "Running $script"
-            node $script
+            node $script || echo "Error running $script" >> error.log
           done
+
       - name: Upload error logs
         if: failure()
         uses: actions/upload-artifact@v2
         with:
           name: error-logs
           path: error.log
+
+      - name: Save full logs
+        if: failure()
+        run: cat error.log
+
       - name: Report success
         if: success()
         run: echo "Scraping completed successfully."
